# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up JDK 8

      uses: actions/setup-java@v2

      with:

        java-version: '8'

        distribution: 'adopt'
    - name: Grant execute permission for gradlew

      run: chmod +x gradlew

    - name: Wrap with Gradle

      run: ./gradlew wrapper --gradle-version=7.1.1 --distribution-type=bin

    - name: Dep with Gradle

      run: ./gradlew dependencies

    - name: Test with Gradle

      run: ./gradlew test

    - name: Build with Gradle

      run: ./gradlew build

      

    - name: Archive artifacts 

      uses: actions/upload-artifact@v2

      if: success()

      with:

          name: GriefDefender

          path: build/libs/*

    #- name: Archive artifacts (GriefDefender)

      #uses: actions/upload-artifact@v1

     # if: success()

    #  with:

        #name: GriefDefender

       # path: bukkit/target/GriefDefender 1.5.10.jar


